# """add newsletter campaign field

# Revision ID: 08f4017a1bc9
# Revises: 815d3b492e08
# Create Date: 2026-07-13 11:24:36.291462

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '08f4017a1bc9'
# down_revision: Union[str, Sequence[str], None] = '815d3b492e08'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('NewsletterBlogSetting',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('enabled', sa.Boolean(), nullable=True),
#     sa.Column('template_id', sa.Integer(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('NewsletterCampaign',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('subject', sa.String(length=255), nullable=False),
#     sa.Column('body', sa.Text(), nullable=False),
#     sa.Column('audience_type', sa.String(length=20), nullable=False),
#     sa.Column('subscriber_ids', sa.JSON(), nullable=True),
#     sa.Column('template_id', sa.Integer(), nullable=True),
#     sa.Column('status', sa.String(length=30), nullable=False),
#     sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('recipient_count', sa.Integer(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
#     sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('blog_url', sa.Text(), nullable=True),
#     sa.Column('auto_send', sa.Boolean(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('NewsletterRecipient',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('campaign_id', sa.Integer(), nullable=True),
#     sa.Column('subscriber_id', sa.Integer(), nullable=True),
#     sa.Column('status', sa.String(length=20), nullable=True),
#     sa.Column('opened', sa.Boolean(), nullable=True),
#     sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('NewsletterSignupSettings',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('heading', sa.String(length=255), nullable=True),
#     sa.Column('intro', sa.Text(), nullable=True),
#     sa.Column('bullets', sa.JSON(), nullable=True),
#     sa.Column('button_text', sa.String(length=50), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('NewsletterTemplate',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('title', sa.String(length=100), nullable=True),
#     sa.Column('subject', sa.String(length=255), nullable=True),
#     sa.Column('body', sa.Text(), nullable=True),
#     sa.Column('category', sa.String(length=50), nullable=True),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('testimonials',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('full_name', sa.String(length=150), nullable=False),
#     sa.Column('designation', sa.String(length=150), nullable=True),
#     sa.Column('company', sa.String(length=150), nullable=True),
#     sa.Column('testimonial_text', sa.Text(), nullable=False),
#     sa.Column('rating', sa.Integer(), nullable=False),
#     sa.Column('profile_image', sa.Text(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
#     op.add_column('Blog', sa.Column('slug', sa.String(length=220), nullable=False))
#     op.add_column('Blog', sa.Column('schema_markup', sa.JSON(), nullable=True))
#     op.add_column('Blog', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
#     op.add_column('Blog', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
#     op.add_column('Blog', sa.Column('published', sa.Boolean(), nullable=True))
#     op.create_index(op.f('ix_Blog_slug'), 'Blog', ['slug'], unique=True)
#     op.alter_column('NewsFeed', 'feed_type',
#                existing_type=sa.VARCHAR(length=100),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.add_column('Newsletter', sa.Column('name', sa.String(length=150), nullable=True))
#     op.add_column('Newsletter', sa.Column('status', sa.String(length=30), nullable=False))
#     op.add_column('Newsletter', sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
#     op.add_column('Newsletter', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
#     op.add_column('Portfolio', sa.Column('url_slug', sa.String(length=255), nullable=False))
#     op.create_index(op.f('ix_Portfolio_url_slug'), 'Portfolio', ['url_slug'], unique=True)
#     op.add_column('career_applications', sa.Column('image_url', sa.String(), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('career_applications', 'image_url')
#     op.drop_index(op.f('ix_Portfolio_url_slug'), table_name='Portfolio')
#     op.drop_column('Portfolio', 'url_slug')
#     op.drop_column('Newsletter', 'updated_at')
#     op.drop_column('Newsletter', 'subscribed_at')
#     op.drop_column('Newsletter', 'status')
#     op.drop_column('Newsletter', 'name')
#     op.alter_column('NewsFeed', 'feed_type',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=100),
#                existing_nullable=False)
#     op.drop_index(op.f('ix_Blog_slug'), table_name='Blog')
#     op.drop_column('Blog', 'published')
#     op.drop_column('Blog', 'updated_at')
#     op.drop_column('Blog', 'created_at')
#     op.drop_column('Blog', 'schema_markup')
#     op.drop_column('Blog', 'slug')
#     op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
#     op.drop_table('testimonials')
#     op.drop_table('NewsletterTemplate')
#     op.drop_table('NewsletterSignupSettings')
#     op.drop_table('NewsletterRecipient')
#     op.drop_table('NewsletterCampaign')
#     op.drop_table('NewsletterBlogSetting')
#     # ### end Alembic commands ###



"""add newsletter campaign field

Revision ID: 08f4017a1bc9
Revises: 815d3b492e08
Create Date: 2026-07-13 11:24:36.291462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08f4017a1bc9'
down_revision: Union[str, Sequence[str], None] = '815d3b492e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """

    # NewsletterCampaign table already exists
    # Created in previous migration.
    # No duplicate create_table here.

    pass


def downgrade() -> None:
    """
    Downgrade schema.
    """

    pass