"""add slug and schema_markup to blog

Revision ID: 195fbfb40f06
Revises: 3046f8b3d9c9
Create Date: 2026-07-04 02:43:19.518546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195fbfb40f06'
down_revision: Union[str, Sequence[str], None] = '3046f8b3d9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog', sa.Column('slug', sa.String(length=220), nullable=True))
    op.add_column('Blog', sa.Column('schema_markup', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_Blog_slug'), 'Blog', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Blog_slug'), table_name='Blog')
    op.drop_column('Blog', 'schema_markup')
    op.drop_column('Blog', 'slug')
    # ### end Alembic commands ###
