"""add newsletter management tables

Revision ID: 2900e418b3e1
Revises: adf599cfe7e7
Create Date: 2026-07-08 21:33:30.490200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2900e418b3e1'
down_revision: Union[str, Sequence[str], None] = 'adf599cfe7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewsletterCampaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewsletterRecipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewsletterSignupSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('bullets', sa.JSON(), nullable=True),
    sa.Column('button_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewsletterTemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Newsletter', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column(
    'Newsletter',
    sa.Column(
        'status',
        sa.String(length=30),
        nullable=True
    )
    )

    op.execute("""
    UPDATE "Newsletter"
    SET status='ACTIVE'
    WHERE status IS NULL
    """)

    op.alter_column(
    'Newsletter',
    'status',
    nullable=False
    ) 
    op.add_column('Newsletter', sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Newsletter', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('Newsletter', 'updated_at')
    op.drop_column('Newsletter', 'subscribed_at')
    op.drop_column('Newsletter', 'status')
    op.drop_column('Newsletter', 'name')
    op.drop_table('NewsletterTemplate')
    op.drop_table('NewsletterSignupSettings')
    op.drop_table('NewsletterRecipient')
    op.drop_table('NewsletterCampaign')
    # ### end Alembic commands ###



# op.add_column('Portfolio', sa.Column('url_slug', sa.String(length=255), nullable=False))
    # op.create_index(op.f('ix_Portfolio_url_slug'), 'Portfolio', ['url_slug'], unique=True)
    # op.add_column('career_applications', sa.Column('image_url', sa.String(), nullable=True))


    # op.drop_column('career_applications', 'image_url')
    # op.drop_index(op.f('ix_Portfolio_url_slug'), table_name='Portfolio')
    # op.drop_column('Portfolio', 'url_slug')