"""initial migration

Revision ID: 3046f8b3d9c9
Revises: 
Create Date: 2026-06-10 18:48:26.861998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3046f8b3d9c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('hash_password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_Admin_id'), 'Admin', ['id'], unique=False)
    op.create_table('Blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('featured_image', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=60), nullable=False),
    sa.Column('meta_description', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Blog_id'), 'Blog', ['id'], unique=False)
    op.create_table('Contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('project_file', sa.Text(), nullable=True),
    sa.Column('completion_date', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Contact_id'), 'Contact', ['id'], unique=False)
    op.create_table('ContactUs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ContactUs_id'), 'ContactUs', ['id'], unique=False)
    op.create_table('Newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Newsletter_id'), 'Newsletter', ['id'], unique=False)
    op.create_table('Portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=200), nullable=False),
    sa.Column('category_node', sa.String(length=100), nullable=False),
    sa.Column('deployment_year', sa.String(length=10), nullable=False),
    sa.Column('primary_image', sa.Text(), nullable=False),
    sa.Column('business_challenge', sa.Text(), nullable=False),
    sa.Column('solution_node', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Portfolio_id'), 'Portfolio', ['id'], unique=False)
    op.create_table('Service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_title', sa.String(length=100), nullable=False),
    sa.Column('url_slug', sa.String(length=150), nullable=False),
    sa.Column('category_stack', sa.String(length=100), nullable=False),
    sa.Column('lucide_icon', sa.String(length=100), nullable=False),
    sa.Column('image_source_type', sa.String(length=50), nullable=False),
    sa.Column('image_showcase_url', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('feature_1', sa.Text(), nullable=True),
    sa.Column('feature_2', sa.Text(), nullable=True),
    sa.Column('feature_3', sa.Text(), nullable=True),
    sa.Column('feature_4', sa.Text(), nullable=True),
    sa.Column('why_choose_1', sa.Text(), nullable=True),
    sa.Column('why_choose_2', sa.Text(), nullable=True),
    sa.Column('why_choose_3', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_slug')
    )
    op.create_index(op.f('ix_Service_id'), 'Service', ['id'], unique=False)
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('bio_description', sa.Text(), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=False),
    sa.Column('facebook_link', sa.Text(), nullable=True),
    sa.Column('instagram_link', sa.Text(), nullable=True),
    sa.Column('linkedin_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Team_id'), 'Team', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Team_id'), table_name='Team')
    op.drop_table('Team')
    op.drop_index(op.f('ix_Service_id'), table_name='Service')
    op.drop_table('Service')
    op.drop_index(op.f('ix_Portfolio_id'), table_name='Portfolio')
    op.drop_table('Portfolio')
    op.drop_index(op.f('ix_Newsletter_id'), table_name='Newsletter')
    op.drop_table('Newsletter')
    op.drop_index(op.f('ix_ContactUs_id'), table_name='ContactUs')
    op.drop_table('ContactUs')
    op.drop_index(op.f('ix_Contact_id'), table_name='Contact')
    op.drop_table('Contact')
    op.drop_index(op.f('ix_Blog_id'), table_name='Blog')
    op.drop_table('Blog')
    op.drop_index(op.f('ix_Admin_id'), table_name='Admin')
    op.drop_table('Admin')
    # ### end Alembic commands ###
