"""add career application table and more 

Revision ID: 5c1edd4c3d37
Revises: 08f4017a1bc9
Create Date: 2026-07-13 14:25:43.893118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1edd4c3d37'
down_revision: Union[str, Sequence[str], None] = '08f4017a1bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
# def upgrade() -> None:
#     """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('NewsFeed',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=200), nullable=False),
    # sa.Column('feed_type', sa.String(length=50), nullable=False),
    # sa.Column('description', sa.Text(), nullable=False),
    # sa.Column('author', sa.String(length=100), nullable=False),
    # sa.Column('event_date', sa.String(length=100), nullable=True),
    # sa.Column('media_url', sa.Text(), nullable=True),
    # sa.Column('is_published', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_NewsFeed_id'), 'NewsFeed', ['id'], unique=False)
    # op.create_table('NewsletterBlogSetting',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('enabled', sa.Boolean(), nullable=True),
    # sa.Column('template_id', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('career_applications',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('company_name', sa.String(), nullable=True),
    # sa.Column('first_name', sa.String(), nullable=False),
    # sa.Column('last_name', sa.String(), nullable=False),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.Column('linkedin_url', sa.String(), nullable=False),
    # sa.Column('cv_url', sa.String(), nullable=False),
    # sa.Column('show_contact_public', sa.Boolean(), nullable=True),
    # sa.Column('image_url', sa.String(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_career_applications_id'), 'career_applications', ['id'], unique=False)
    # op.create_table('testimonials',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('full_name', sa.String(length=150), nullable=False),
    # sa.Column('designation', sa.String(length=150), nullable=True),
    # sa.Column('company', sa.String(length=150), nullable=True),
    # sa.Column('testimonial_text', sa.Text(), nullable=False),
    # sa.Column('rating', sa.Integer(), nullable=False),
    # sa.Column('profile_image', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
    # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    # op.drop_table('testimonials')
    # op.drop_index(op.f('ix_career_applications_id'), table_name='career_applications')
    # op.drop_table('career_applications')
    # op.drop_table('NewsletterBlogSetting')
    # op.drop_index(op.f('ix_NewsFeed_id'), table_name='NewsFeed')
    # op.drop_table('NewsFeed')
    # ### end Alembic commands ###
