"""add newsletter campaign fields

Revision ID: 815d3b492e08
Revises: 2900e418b3e1
Create Date: 2026-07-09 00:23:15.657272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815d3b492e08'
down_revision: Union[str, Sequence[str], None] = '2900e418b3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsletterCampaign', sa.Column('subscriber_ids', sa.JSON(), nullable=True))
    op.add_column('NewsletterCampaign', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('NewsletterCampaign', sa.Column('blog_url', sa.Text(), nullable=True))
    op.add_column('NewsletterCampaign', sa.Column('auto_send', sa.Boolean(), nullable=True))
    op.add_column('Portfolio', sa.Column('url_slug', sa.String(length=255), nullable=True))
    op.execute("""
        UPDATE "Portfolio"
        SET url_slug = LOWER(
            REPLACE(project_title, ' ', '-')
        )
        WHERE url_slug IS NULL
    """)


    op.alter_column(
        'Portfolio',
        'url_slug',
        nullable=False
    )


    op.create_index(
        'ix_Portfolio_url_slug',
        'Portfolio',
        ['url_slug'],
        unique=True
    )
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    op.drop_column('Portfolio', 'url_slug')
    op.drop_column('NewsletterCampaign', 'auto_send')
    op.drop_column('NewsletterCampaign', 'blog_url')
    op.drop_column('NewsletterCampaign', 'template_id')
    op.drop_column('NewsletterCampaign', 'subscriber_ids')
    # ### end Alembic commands ###


# op.create_index(op.f('ix_Portfolio_url_slug'), 'Portfolio', ['url_slug'], unique=True)
# op.drop_index(op.f('ix_Portfolio_url_slug'), table_name='Portfolio')


# op.add_column('career_applications', sa.Column('image_url', sa.String(), nullable=True))
# op.drop_column('career_applications', 'image_url')