"""add blog improvements

Revision ID: adf599cfe7e7
Revises: 195fbfb40f06
Create Date: 2026-07-06 20:47:28.044049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf599cfe7e7'
down_revision: Union[str, Sequence[str], None] = '195fbfb40f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Blog', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Blog', sa.Column('published', sa.Boolean(), nullable=True))
    op.alter_column('Blog', 'slug',
               existing_type=sa.VARCHAR(length=220),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Blog', 'slug',
               existing_type=sa.VARCHAR(length=220),
               nullable=True)
    op.drop_column('Blog', 'published')
    op.drop_column('Blog', 'updated_at')
    op.drop_column('Blog', 'created_at')
    # ### end Alembic commands ###
